apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g60yhw61c-go
  janus-idp.io/tekton: g60yhw61c-go
  backstage.io/kubernetes-id: g60yhw61c-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g60yhw61c-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
